### ISSUE TITLE
Create test

### ISSUE THREAD

**Issue by stivaliserna** [FabricElements/skeleton-auth#14]
- [x]  Validate incorrect input for email, name and password

- [ ] Return right provider when the user try to sign in with one that is not set up for that user

**Comment by ernysans** [comment]
@stivaliserna I just updated the component, the validation test aren't passing. You need to change the value of the input input to validate. I did this change to prevent the validation if the input is empty.

**Comment by ernysans** [comment]
@stivaliserna Please fix the test test.
