### ISSUE TITLE
How to add the firebase configuration?

### ISSUE THREAD

**Issue by MarcusGV** [FabricElements/skeleton-auth#54]
Hi, your work sound great! congratulations, but I am just starting and I can't find where can I put the firebase configuration, how I do that?, thanks again.

{
      apiKey: "",
      authDomain: "",
      databaseURL: "",
      projectId: "",
      storageBucket: "",
      messagingSenderId: ""
  }

**Comment by ernysans** [comment]
Hi @MarcusGV, you can use the default `firebase.initializeApp`

**Comment by MarcusGV** [comment]
Thanks, almost works :) Im using the polymer starter kit with polymer 3, but now I have another problem and I dont know why :( , could you help me? when I click on the google button for example to login, I got this errors :(, but I cant find where is the problem :(, sorry Im just starting :(

![error2](https://user-images.githubusercontent.com/39317911/54073519-ab938e80-424d-11e9-9bd3-5074a21d3653.jpg)
![Error1](https://user-images.githubusercontent.com/39317911/54073520-ab938e80-424d-11e9-9fcf-7ba11fa791a3.jpg)

**Comment by ernysans** [comment]
Hi @MarcusGV, that has nothing to do with the component, you only need to import firebase on your index file and start firebase app there, you are probably setting up something wrong on your end on your firebase.json, or looks like there is something wrong with your build
